#! /bin/zsh

# Omit "cd"
setopt AUTO_CD

setopt CORRECT

alias airport='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport'
alias ll='ls -AlG'
alias ls='ls -G'

export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
