#! /bin/zsh

alias airport='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport'
alias ll='ls -AlGh'
alias ls='ls -Gh'

export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
export TERM=xterm-256color
