#! /bin/zsh

alias ll='ls --color=always --group-directories-first -Alh'
alias ls='ls --color=always --group-directories-first -h'

export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

function tmux_list_pids() {
	for s in `tmux list-sessions -F '#{session_name}'` ; do
		echo -e "\ntmux session name: $s\n--------------------"
		for p in `tmux list-panes -s -F '#{pane_pid}' -t "$s"` ; do
			pstree -p -a -A $p
		done
	done
}

zstyle ':completion:*:default' menu select yes
