#! /bin/zsh

# Adapted from http://www.spinics.net/lists/git/msg142043.html
git-clean () {

    # This is going to be called every PRECMD, so let's say that
    # updating the index every time we hit returns is a bit too much
    # # Update the index
    # git update-index -q --ignore-submodules --refresh

    # Disallow unstaged changes in the working tree
    if ! $(git diff-files --quiet --ignore-submodules --); then
        return 1
    fi

    # Disallow uncommitted changes in the index
    if ! $(git diff-index --cached --quiet HEAD --ignore-submodules --); then
        return 1
    fi

    return 0
}