#! /bin/zsh

typeset -Ag M4PROMPT

#	KEY			MEANING
#	------------------------------------------------
# 	readonly	Current folder has now write access
#	git			Current folder has git information
#

M4PROMPT=(readonly -1 git -1)

# Use ZSH hooks for handling the prompt change
autoload -U add-zsh-hook

# Style information
local dir_fg dir_bg usr_fg usr_bg su_fg su_bg

dir_fg=022
dir_bg=193
usr_fg=006
usr_bg=023
su_fg=210
su_bg=052

segment() {
	readonly separator='\ue0b0'

	# $1: new foreground
	# $2: new background

	if [[ $cur_bg -eq -1 ]]; then

		# BEGIN, just set the color
		echo -n "%{%F{$1}%}%{%K{$2}%} "
		cur_bg=$2

	elif [[ $1 -eq -1 ]]; then

		# END, deactivate and clear
		echo -n " %{%F{$cur_bg}%}%{%k%}$separator%{%f%} "
		cur_bg=-1

	else

		# INTERMEDIATE!
		echo -n " %{%F{$cur_bg}%}%{%K{$2}%}$separator%{%F{$1}%} "
		cur_bg=$2

	fi
}


prompt_usr() {
	# Choose between root and normal user scheme
	echo -n "%(!."
	segment $su_fg $su_bg
	echo -n "."
	segment $usr_fg $usr_bg
	echo -n ")%n"

}

prompt_dir() {
	segment $dir_fg $dir_bg
	echo -n "%30<…<%~%<<"
	# Check if writable
	if ! [[ -w . ]]; then
		echo -n " \ue0a2"	# locket
	fi
}

build_prompt() {
	local cur_bg=-1

	prompt_usr
	prompt_dir

	segment -1
}


precmd() {
	PROMPT="$(build_prompt)"
}
