#!/usr/bin/zsh
do-tex() {
	local SUFFIX
	is-git && SUFFIX=$(get-git-current-commit) || SUFFIX=$(TZ=Europe/Rome date "+%Y-%m-%d_%H:%M:%S")
	TEX_JOBNAME="${$(basename "$1")%.*}_${SUFFIX}"
	TEX_JOBNAME=${TEX_JOBNAME:gs/ /_/}
	latexmk -e '$latex=q/latex %O -shell-escape %S/' -C "$1"
	latexmk -e '$latex=q/latex %O -shell-escape %S/' -pdf -jobname="$TEX_JOBNAME" "$1"
	latexmk -e '$latex=q/latex %O -shell-escape %S/' -c -jobname="$TEX_JOBNAME" "$1"
}
